
window.Box=window.Box||{};Box.Timing=Box.Timing||{execution:[],scripts:{},events:{}};Box.Timing.scripts['contextual_message']=(new Date()).getTime();Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/contextual-message.js',time:(new Date()).getTime()});Box.Application.addService('contextual-message',function(application){'use strict';var MARK_MESSAGE_AS_SEEN_RUNMODE='contextual_message_mark_as_seen';var MARK_MESSAGE_AS_CLOSED_RUNMODE='contextual_message_mark_as_closed';var REFRESH_PREVIEW_CONTENT='previewrefreshrequested';var TYPE_BANNER='banner';var TYPE_FULLSCREENTOUR='fullscreentour';var TYPE_MODAL='modal';var TYPE_POPOUT='popout';var pigeon={};var needsPreviewRefresh=[TYPE_FULLSCREENTOUR];var needsHotkeysDisabled=[TYPE_MODAL,TYPE_FULLSCREENTOUR,TYPE_POPOUT];var canCoexistWithOtherTypes=[TYPE_BANNER];var shouldDisableHotkeys=false;function canMessageTypesCoexist(messageType1,messageType2){return(messageType1!==messageType2)&&(canCoexistWithOtherTypes.indexOf(messageType1)>-1||canCoexistWithOtherTypes.indexOf(messageType2)>-1);}
function canCoexistWithCurrentlyShownMessages(currentlyShownMessages,messageToBeShown){var currentlyShownMessageTypes=Object.keys(currentlyShownMessages);var length=currentlyShownMessageTypes.length;for(var i=0;i<length;i++){if(!canMessageTypesCoexist(currentlyShownMessageTypes[i],messageToBeShown.type)){return false;}}
return true;}
function requestPreviewRefresh(messageType){if(needsPreviewRefresh.indexOf(messageType)>-1){application.broadcast(REFRESH_PREVIEW_CONTENT);}}
function setShouldDisabledHotkeys(messageType,shouldDisable){if(needsHotkeysDisabled.indexOf(messageType)>-1){shouldDisableHotkeys=shouldDisable;}}
function startMessageModuleIfNeeded(messageEl){if(!messageEl){return;}
var moduleEl=application.getService('dom').query('[data-module]',messageEl);if(moduleEl&&!application.isStarted(moduleEl)){application.start(moduleEl);}}
function markMessageAsSeen(messageId,messageIdentifier,messageContext){application.getService('ajax').post(MARK_MESSAGE_AS_SEEN_RUNMODE,{id:messageId,identifier:messageIdentifier,context:messageContext});}
function markMessageAsClosed(messageId,messageIdentifier,messageContext,wasTriggeredByUserAction){application.getService('ajax').post(MARK_MESSAGE_AS_CLOSED_RUNMODE,{id:messageId,identifier:messageIdentifier,context:messageContext,wasTriggeredByUserAction:wasTriggeredByUserAction});}
function onMessageLoaded(){}
function onMessageShown(messageHolder){var message=messageHolder.message;requestPreviewRefresh(message.type);setShouldDisabledHotkeys(message.type,true);startMessageModuleIfNeeded(message.el);markMessageAsSeen(message.id,message.identifier,message.context);}
function onMessageClosed(messageHolder){var message=messageHolder.message;markMessageAsClosed(message.id,message.identifier,message.context,messageHolder.wasTriggeredByUserAction);requestPreviewRefresh(message.type);setShouldDisabledHotkeys(message.type,false);}
function addMessageRepresentationFactoryIfPossible(factoryName){if(application.hasService(factoryName)){pigeon.addMessageRepresentationFactory(factoryName,application.getService(factoryName));}}
function init(){if(!application.hasService('pigeon')){throw new Error('contextual-message.js#init : contextual-message service should be available for this service to work');}
pigeon=application.getService('pigeon');pigeon.registerGlobalOnLoadCallback(onMessageLoaded).registerGlobalOnShowCallback(onMessageShown).registerGlobalOnCloseCallback(onMessageClosed).setCanMessagesCoexistEvaluator(canCoexistWithCurrentlyShownMessages);addMessageRepresentationFactoryIfPossible(TYPE_BANNER);addMessageRepresentationFactoryIfPossible(TYPE_FULLSCREENTOUR);addMessageRepresentationFactoryIfPossible(TYPE_MODAL);addMessageRepresentationFactoryIfPossible(TYPE_POPOUT);}
init();return{registerMessage:function(message){pigeon.registerMessage(message);},unregisterMessage:function(messageIdentifier,messageContext,messageType){pigeon.unregisterMessage(messageIdentifier,messageContext,messageType);},createMessageRepresentation:function(messageName,messageType){return pigeon.createMessageRepresentation(messageName,messageType);},createMessageRepresentationWithContext:function(messageName,messageType,messageContext){return pigeon.createMessageRepresentationWithContext(messageName,messageType,messageContext);},shouldDisableHotkeys:function(){return shouldDisableHotkeys;}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/factories/fullscreentour.js',time:(new Date()).getTime()});Box.Application.addService('fullscreentour',function(application){'use strict';var ESC_KEY=27;var LEFT_ARROW_KEY=37;var RIGHT_ARROW_KEY=39;var TIME_TO_MAKE_TOUR_VISIBLE=600;var CLASS_DISABLE_SELECTABLE='disable_selectable';var CLASS_FULLSCREEN_TOUR_BODY='fullscreen-tour';var CLASS_HIDDEN='hidden';var CLASS_HIDE_OVERFLOW='hide-overflow';var CLASS_IS_ACTIVE='is-active';var CLASS_NO_TRANSITION='no-transition';var CLASS_TOUR_SHIM='fullscreen-tour-shim';var ajaxService=application.getService('ajax');var carouselFactory=application.getService('slide-carousel');var domService=application.getService('dom');var promisesService=application.getService('promises');var resinService=application.getService('resin');var screenService=application.getService('screen');var currentTour=null;var carousel;var fakeBodyEl;var window=application.getGlobal('window');var requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame;var resinActionAttributes;function noop(){}
function getCurrentTourName(){return(currentTour!==null)?currentTour.tourData.name:null;}
function getCurrentPageName(){return resinService.sanitize(resinActionAttributes.page);}
function recordUserActionProgrammatically(target,action){resinService.recordAction({application:resinService.sanitize(resinActionAttributes.application),page:currentTour.tourEl.getAttribute('data-resin-page'),component:'none',feature:'fullscreentour',target:resinService.sanitize(target),action:resinService.sanitize(action)});}
function updateResinPage(){var resinPage=getCurrentPageName()+'|'+getCurrentTourName()+'|'+(carousel.getCurrentSlideName());currentTour.tourEl.setAttribute('data-resin-page',resinService.sanitize(resinPage));}
function initResinAttributes(){currentTour.tourEl.removeAttribute('data-resin-page');var resinTarget=currentTour.tourEl.firstChild;resinActionAttributes=resinService.getActionAttributes(resinTarget);updateResinPage();}
function getVideoFromCurrentSlide(slideName){return(slideName)?domService.query('[data-slide-name="'+slideName+'"] video',currentTour.tourEl):null;}
function pauseVideo(slideName){var videoEl=getVideoFromCurrentSlide(slideName);if(videoEl&&videoEl.pause){videoEl.pause();videoEl.currentTime=0;}}
function startVideo(slideName){var videoEl=getVideoFromCurrentSlide(slideName);if(videoEl&&videoEl.play){videoEl.play();}}
function appendChild(el,parentTargetEl){parentTargetEl.appendChild(el);}
function makeTourVisible(){domService.removeClass(currentTour.tourEl,CLASS_HIDDEN);}
function moveTourElementInsideBody(){appendChild(currentTour.tourEl,document.body);}
function resetAndHideTour(){domService.removeClass(domService.query('.slide.is-active',currentTour.tourEl),CLASS_IS_ACTIVE);domService.addClass(currentTour.tourEl,CLASS_HIDDEN);}
function moveAllChildElements(fromEl,toEl){while(fromEl.childNodes.length>0){appendChild(fromEl.childNodes[0],toEl);}}
function resetSlidePosition(){carousel.goToSlide(0);}
function resizeFakeBodyEl(event,shouldAnimate){var transparentSlideEl=domService.query('.slide .transparent',currentTour.tourEl);if(!transparentSlideEl){return;}
var slideClientRect=domService.getBoundingClientRect(transparentSlideEl);if(!shouldAnimate){domService.addClass(fakeBodyEl,CLASS_NO_TRANSITION);}
fakeBodyEl.style.left=slideClientRect.left+'px';fakeBodyEl.style.top=slideClientRect.top+'px';fakeBodyEl.style.width=slideClientRect.width+'px';fakeBodyEl.style.height=slideClientRect.height+'px';if(!shouldAnimate){requestAnimationFrame(function(){domService.removeClass(fakeBodyEl,CLASS_NO_TRANSITION);});}}
function displayShimForTour(){var bodyShim=document.createElement('div');bodyShim.className=CLASS_TOUR_SHIM;appendChild(bodyShim,document.body);}
function hideShimAfterTour(){var bodyShim=domService.query('.'+CLASS_TOUR_SHIM);bodyShim.parentNode.removeChild(bodyShim);}
function preparePageForTour(shouldShowTourWithAnimation){if(!shouldShowTourWithAnimation){displayShimForTour();return;}
var tempFakeBodyContainerEl;tempFakeBodyContainerEl=document.createElement('div');tempFakeBodyContainerEl.className='tour-fullscreen-fake-body-container tour-flex-container tour-full-abs-pos';fakeBodyEl=document.createElement('div');fakeBodyEl.className='tour-fullscreen-fake-body tour-full-abs-pos '+CLASS_IS_ACTIVE;appendChild(fakeBodyEl,tempFakeBodyContainerEl);moveAllChildElements(document.body,fakeBodyEl);appendChild(tempFakeBodyContainerEl,document.body);}
function resetBodyAfterTour(shouldShowTourWithAnimation){if(!shouldShowTourWithAnimation){hideShimAfterTour();return;}
moveAllChildElements(fakeBodyEl,document.body);document.body.removeChild(fakeBodyEl.parentNode);fakeBodyEl=null;}
function registerTransitionEventCallbacks(transitioningEl,callback){function onTourStartTransitionEnd(){domService.off(transitioningEl,'transitionend',onTourStartTransitionEnd);callback();}
domService.on(transitioningEl,'transitionend',onTourStartTransitionEnd);}
function isTourBeingShownWithAnimation(){return currentTour&&currentTour.tourEl&&currentTour.tourEl.getAttribute('data-hide-animation')==='false';}
function setFakeBodyClass(isActive){if(!isTourBeingShownWithAnimation()){return;}
if(isActive){domService.addClass(fakeBodyEl,CLASS_IS_ACTIVE);}else{domService.removeClass(fakeBodyEl,CLASS_IS_ACTIVE);}}
function setDocumentBodyClasses(shouldShowTourWithAnimation){if(!shouldShowTourWithAnimation){domService.addClass(document.body,CLASS_HIDE_OVERFLOW);}
domService.addClass(document.body,CLASS_FULLSCREEN_TOUR_BODY);domService.addClass(document.body,CLASS_DISABLE_SELECTABLE);}
function removeDocumentBodyClasses(shouldShowTourWithAnimation){if(!shouldShowTourWithAnimation){domService.removeClass(document.body,CLASS_HIDE_OVERFLOW);}
domService.removeClass(document.body,CLASS_FULLSCREEN_TOUR_BODY);domService.removeClass(document.body,CLASS_DISABLE_SELECTABLE);}
function resizeBodyForTour(){resizeFakeBodyEl(null,true);}
function createTourShowAnimation(){setTimeout(function(){makeTourVisible();startVideo(carousel.getCurrentSlideName());},TIME_TO_MAKE_TOUR_VISIBLE);domService.addClass(domService.query('.'+CLASS_TOUR_SHIM),CLASS_IS_ACTIVE);}
function createAnimationScaffold(){var shouldShowTourWithAnimation=isTourBeingShownWithAnimation();preparePageForTour(shouldShowTourWithAnimation);moveTourElementInsideBody();if(shouldShowTourWithAnimation){domService.on(window,'resize',resizeFakeBodyEl);registerTransitionEventCallbacks(fakeBodyEl,resetSlidePosition);setDocumentBodyClasses(shouldShowTourWithAnimation);makeTourVisible();resizeBodyForTour();}else{resetSlidePosition();setDocumentBodyClasses(shouldShowTourWithAnimation);requestAnimationFrame(createTourShowAnimation);}}
function destroyAnimationScaffold(){var shouldShowTourWithAnimation=isTourBeingShownWithAnimation();if(shouldShowTourWithAnimation){domService.off(window,'resize',resizeFakeBodyEl);}
resetBodyAfterTour(shouldShowTourWithAnimation);resetAndHideTour();moveTourElementInsideBody();removeDocumentBodyClasses();}
function closeTour(){detachTourListeners();if(currentTour){pauseVideo(carousel.getCurrentSlideName());destroyAnimationScaffold();currentTour.tourEl=null;carousel.destroy();currentTour.onCloseCallback();}
currentTour=null;}
function goToNextSlide(){if(!currentTour){return;}
pauseVideo(carousel.getCurrentSlideName());carousel.goToNextSlide();if(carousel.currentSlideNum>0&&isTourBeingShownWithAnimation()){setFakeBodyClass(false);}
startVideo(carousel.getCurrentSlideName());recordUserActionProgrammatically('next','click');updateResinPage();recordUserActionProgrammatically('loaded','programmatic');}
function goToPreviousSlide(){if(!currentTour){return;}
pauseVideo(carousel.getCurrentSlideName());carousel.goToPrevSlide();if(carousel.currentSlideNum<=0&&isTourBeingShownWithAnimation()){setFakeBodyClass(true);}
startVideo(carousel.getCurrentSlideName());recordUserActionProgrammatically('previous','click');updateResinPage();recordUserActionProgrammatically('loaded','programmatic');}
function mouseUpHandler(event){var element=event.target||event.srcElement;var action=element.getAttribute('data-action');if(action==='carousel-previous'){goToPreviousSlide();}else if(action==='carousel-next'){goToNextSlide();}else if(action==='carousel-end'){closeTour();}}
function keyUpHandler(event){var key=event.keyCode;if(key===LEFT_ARROW_KEY){goToPreviousSlide();}else if(key===RIGHT_ARROW_KEY){goToNextSlide();}else if(key===ESC_KEY){recordUserActionProgrammatically('close|esc','keypress');closeTour();}}
function attachTourListeners(){domService.on(document.body,'mouseup',mouseUpHandler);domService.on(document.body,'keyup',keyUpHandler);}
function detachTourListeners(){domService.off(document.body,'mouseup',mouseUpHandler);domService.off(document.body,'keyup',keyUpHandler);}
function showTour(){attachTourListeners();carousel=carouselFactory.create(currentTour.tourEl);createAnimationScaffold();document.body.focus();initResinAttributes();recordUserActionProgrammatically('loaded','programmatic');var callbackData=$.extend({},currentTour.tourData,{el:currentTour.tourEl});currentTour.onShowCallback(callbackData);}
function loadTour(tour){var tourEl=domService.query('[data-tour-name="'+tour.tourData.name+'"]');var runmode=tour.tourData.templateFetchEndpoint;var params={id:tour.tourData.id,identifier:tour.tourData.identifier,isHighDensityDisplay:screenService.isHighDensity()};if(tourEl){tour.onLoadCallback(tour.tourData);return promisesService.createResolved();}
return ajaxService.get(runmode,params).then(function tourContentReceived(response){var tourFragment=domService.createFragmentFromHtml(response.data.html);document.body.appendChild(tourFragment);return;}).then(function executeLoadCallbacks(){tour.onLoadCallback(tour.tourData);return;});}
function FullscreenTour(tourData){this.tourData=tourData;this.tourEl=null;this.onLoadCallback=noop;this.onShowCallback=noop;this.onCloseCallback=noop;}
FullscreenTour.prototype={load:function(){return loadTour(this);},show:function(){var tourName=this.tourData.name;currentTour=this;this.load().then(function(){currentTour.tourEl=domService.query('[data-tour-name="'+tourName+'"]');showTour();});},unload:function(){},setOnLoadCallback:function(callback){if(typeof callback==='function'){this.onLoadCallback=callback;}},setOnShowCallback:function(callback){if(typeof callback==='function'){this.onShowCallback=callback;}},setOnCloseCallback:function(callback){if(typeof callback==='function'){this.onCloseCallback=callback;}},_close:closeTour};return{create:function(tourData){return new FullscreenTour(tourData);}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/factories/modal.js',time:(new Date()).getTime()});Box.Application.addService('modal',function(application){'use strict';var ESC_KEY=27;var LEFT_ARROW_KEY=37;var RIGHT_ARROW_KEY=39;var DISABLE_SELECTABLE_CLASS='disable_selectable';var FINAL_SLIDE_CLASS='final-slide';var HIDDEN_CLASS='hidden';var NO_SCROLL_CLASS='no_scroll';var ajaxService=application.getService('ajax');var carouselFactory=application.getService('slide-carousel');var domService=application.getService('dom');var promisesService=application.getService('promises');var resinService=application.getService('resin');var screenService=application.getService('screen');var currentModal=null;var carousel;var backBtnEl;var resinActionAttributes;function noop(){}
function getCurrentModalName(){return(currentModal!==null)?currentModal.modalData.name:null;}
function getCurrentPageName(){return resinService.sanitize(resinActionAttributes.page);}
function recordUserActionProgrammatically(target,action){resinService.recordAction({application:resinService.sanitize(resinActionAttributes.application),page:currentModal.modalEl.getAttribute('data-resin-page'),component:'none',feature:'modal',target:resinService.sanitize(target),action:resinService.sanitize(action)});}
function updateResinPage(){var resinPage=getCurrentPageName()+'|'+getCurrentModalName()+'|'+(carousel.getCurrentSlideName());currentModal.modalEl.setAttribute('data-resin-page',resinService.sanitize(resinPage));}
function initResinAttributes(){currentModal.modalEl.removeAttribute('data-resin-page');var resinTarget=currentModal.modalEl.firstChild;resinActionAttributes=resinService.getActionAttributes(resinTarget);updateResinPage();}
function resetModalButtons(){if(carousel.isOnLastSlide()){domService.addClass(currentModal.modalEl,FINAL_SLIDE_CLASS);}else{domService.removeClass(currentModal.modalEl,FINAL_SLIDE_CLASS);}
if(carousel.currentSlideNum===0){domService.addClass(backBtnEl,HIDDEN_CLASS);}else{domService.removeClass(backBtnEl,HIDDEN_CLASS);}}
function doHideCurrentModal(){domService.addClass(currentModal.modalEl,HIDDEN_CLASS);domService.removeClass(currentModal.modalEl,DISABLE_SELECTABLE_CLASS);domService.removeClass(document.body,NO_SCROLL_CLASS);}
function doShowCurrentModal(){resetModalButtons();domService.removeClass(currentModal.modalEl,HIDDEN_CLASS);domService.addClass(currentModal.modalEl,DISABLE_SELECTABLE_CLASS);domService.addClass(document.body,NO_SCROLL_CLASS);}
function goToNextSlide(){if(!currentModal){return;}
carousel.goToNextSlide();resetModalButtons();recordUserActionProgrammatically('next','click');updateResinPage();recordUserActionProgrammatically('loaded','programmatic');}
function goToPreviousSlide(){if(!currentModal){return;}
carousel.goToPrevSlide();resetModalButtons();recordUserActionProgrammatically('previous','click');updateResinPage();recordUserActionProgrammatically('loaded','programmatic');}
function closeModal(){detachModalListeners();if(currentModal){doHideCurrentModal();carousel.destroy();currentModal.onCloseCallback();}
currentModal=null;}
function mouseUpHandler(event){var element=event.target||event.srcElement;var action=element.getAttribute('data-action');if(action==='carousel-previous'){goToPreviousSlide();}else if(action==='carousel-next'){goToNextSlide();}else if(action==='carousel-end'){closeModal();}}
function keyUpHandler(event){var key=event.keyCode;if(key===LEFT_ARROW_KEY){goToPreviousSlide();}else if(key===RIGHT_ARROW_KEY){goToNextSlide();}else if(key===ESC_KEY){recordUserActionProgrammatically('close|esc','keypress');closeModal();}}
function attachModalListeners(){domService.on(document.body,'mouseup',mouseUpHandler);domService.on(document.body,'keyup',keyUpHandler);}
function detachModalListeners(){domService.off(document.body,'mouseup',mouseUpHandler);domService.off(document.body,'keyup',keyUpHandler);}
function showModal(){attachModalListeners();backBtnEl=domService.query('[data-action="carousel-previous"]',currentModal.modalEl);carousel=carouselFactory.create(currentModal.modalEl);carousel.goToSlide(0);doShowCurrentModal();initResinAttributes();recordUserActionProgrammatically('loaded','programmatic');var callbackData=$.extend({},currentModal.modalData,{el:currentModal.modalEl});currentModal.onShowCallback(callbackData);}
function loadHighResolutionImagesIfNeeded(fragmentOrElement){if(!screenService.isHighDensity()){return fragmentOrElement;}
var figureEls=fragmentOrElement.querySelectorAll('figure');for(var i=0;i<figureEls.length;i++){if(figureEls[i].hasAttribute('data-highres-img')){var image=new Image();image.onload=(function(){var figureEl=figureEls[i];var highResBackgroundImage=figureEl.getAttribute('data-highres-img');return function(){figureEl.style.backgroundImage='url('+highResBackgroundImage+')';figureEl.removeAttribute('data-highres-img');};}());image.src=figureEls[i].getAttribute('data-highres-img');}}
return fragmentOrElement;}
function loadModal(modal){var modalEl=domService.query('[data-modal-name="'+modal.modalData.name+'"]');var runmode=modal.modalData.templateFetchEndpoint;var params={id:modal.modalData.id,identifier:modal.modalData.identifier,isHighDensityDisplay:screenService.isHighDensity()};if(modalEl){loadHighResolutionImagesIfNeeded(modalEl);modal.onLoadCallback(modal.modalData);return promisesService.createResolved();}
return ajaxService.get(runmode,params).then(function modalContentReceived(response){var modalFragment=domService.createFragmentFromHtml(response.data.html);var updatedModalFragment=loadHighResolutionImagesIfNeeded(modalFragment);document.body.appendChild(updatedModalFragment);return;}).then(function executeLoadCallbacks(){modal.onLoadCallback(modal.modalData);return;});}
function Modal(modalData){this.modalData=modalData;this.modalEl=null;this.onLoadCallback=noop;this.onShowCallback=noop;this.onCloseCallback=noop;}
Modal.prototype={load:function(){return loadModal(this);},show:function(){var modalName=this.modalData.name;currentModal=this;this.load().then(function(){currentModal.modalEl=domService.query('[data-modal-name="'+modalName+'"]');showModal();});},unload:function(){},setOnLoadCallback:function(callback){if(typeof callback==='function'){this.onLoadCallback=callback;}},setOnShowCallback:function(callback){if(typeof callback==='function'){this.onShowCallback=callback;}},setOnCloseCallback:function(callback){if(typeof callback==='function'){this.onCloseCallback=callback;}},_close:closeModal};return{create:function(modalData){return new Modal(modalData);}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/message-registration-desk.js',time:(new Date()).getTime()});Box.Application.addService('message-registration-desk',function(){'use strict';var registeredMessages={};function registerMessage(message){if(!(message.identifier in registeredMessages)){registeredMessages[message.identifier]={};}
registeredMessages[message.identifier][message.context]=message;}
function removeMessageFromRegisteredList(messageIdentifier,messageContext){if(messageIdentifier in registeredMessages){if(Object.keys(registeredMessages[messageIdentifier]).length===1){delete registeredMessages[messageIdentifier];}else{delete registeredMessages[messageIdentifier][messageContext];}}}
function getRegisteredMessage(messageIdentifier,messageContext){var registeredMessage;var registeredMessageContexts;if(!(messageIdentifier in registeredMessages)){return null;}
registeredMessage=registeredMessages[messageIdentifier];if(messageContext===null){registeredMessageContexts=Object.keys(registeredMessage);if(registeredMessageContexts.length>1){var errorMsg='Message context needs to be specified when a message has been registered with multiple contexts. ';errorMsg+='[identifier: '+messageIdentifier+']';throw new Error(errorMsg);}
return(registeredMessageContexts.length===1)?registeredMessage[registeredMessageContexts[0]]:null;}
return(messageContext in registeredMessage)?registeredMessage[messageContext]:null;}
function getAllRegisteredMessagesOfType(messageType){var messagesOfType=[];Object.keys(registeredMessages).map(function(identifier){Object.keys(registeredMessages[identifier]).map(function(context){var message=registeredMessages[identifier][context];if(message.type===messageType){messagesOfType.push(message);}});});return messagesOfType;}
return{register:registerMessage,unregister:removeMessageFromRegisteredList,get:getRegisteredMessage,getAllRegisteredMessagesOfType:getAllRegisteredMessagesOfType};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/message-factory-collection.js',time:(new Date()).getTime()});Box.Application.addService('message-factory-collection',function(){'use strict';var messageRepresentationFactories={};function isValidFactory(factory){if(factory.create){return true;}
throw new Error('[message-representation-factory] Should define create method');}
return{add:function(factoryName,factoryService){if(isValidFactory(factoryService)){messageRepresentationFactories[factoryName]=factoryService;}},get:function(factoryName){return messageRepresentationFactories[factoryName]||null;}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/message-auctioneer.js',time:(new Date()).getTime()});Box.Application.addService('message-auctioneer',function(application){'use strict';var DEBOUNCE_PERIOD_IN_MS=50;var ONLOAD_KEY='onLoad';var ONSHOW_KEY='onShow';var ONCLOSE_KEY='onClose';var priorityQueueService=application.getService('priority-queue');var messagesToLoad={};var messagesToShow;var debouncedActionTimeouts={};var messagePreLoadCallbacks=[];var fnMessageEligibilityEvaluator=null;function executeCallbackAfterDebouncingIt(callback,queue){var callbackHash=btoa(callback.toString());if(debouncedActionTimeouts[callbackHash]){return;}
debouncedActionTimeouts[callbackHash]=setTimeout(function(){callback(queue);queue.clear();debouncedActionTimeouts[callbackHash]=null;},DEBOUNCE_PERIOD_IN_MS);}
function compareMessagesByImportance(messageHolder1,messageHolder2){var message1=messageHolder1.message;var message2=messageHolder2.message;var priorityDiff=message2.priority-message1.priority;if(priorityDiff!==0){return priorityDiff;}
var exemptionDiff=(+message2.isExemptFromSuppression)-(+message1.isExemptFromSuppression);if(exemptionDiff!==0){return exemptionDiff;}
var recencyDiff=message2.createdDate-message1.createdDate;return recencyDiff;}
function isMessageEligible(message){if(fnMessageEligibilityEvaluator===null){return true;}
return fnMessageEligibilityEvaluator(message);}
function getEligibleMessageHolderWithHighestPriority(priorityQueue){var messageHolder=null;do{messageHolder=priorityQueue.dequeue();}while(messageHolder!==null&&!isMessageEligible(messageHolder.message));return messageHolder;}
function runAllOnMessagePreLoadCallbacks(message){var fnCallbacks=messagePreLoadCallbacks;for(var i=0,l=fnCallbacks.length;i<l;i++){fnCallbacks[i].call(null,message);}}
function loadMessageWithHighestPriority(priorityQueue){var messageHolder=getEligibleMessageHolderWithHighestPriority(priorityQueue);if(messageHolder!==null){runAllOnMessagePreLoadCallbacks(messageHolder.message);messageHolder.representation.load();}}
function showMessageWithHighestPriority(priorityQueue){var messageHolder=getEligibleMessageHolderWithHighestPriority(priorityQueue);if(messageHolder!==null){messageHolder.representation.show();}}
function queueRequestAndExecuteAction(queue,requestObject,callback){queue.queue(requestObject);executeCallbackAfterDebouncingIt(callback,queue);}
function DisplayableMessage(message,messageRepresentation){this.identifier=message.identifier;this.name=message.name;this.type=message.type;this.context=message.context;this.isTriggeredByUserAction=null;this._representation=messageRepresentation;var callbacks={onLoad:[],onShow:[],onClose:[]};function getMessageHolder(){return{message:message,representation:messageRepresentation};}
function addCallBackHandlerByEventType(type,callback){if(typeof callback!=='function'){return;}
callbacks[type].push(callback);}
function runAllCallBackHandlersByEventType(type,messageHolder){var fnCallbacks=callbacks[type];for(var i=0,l=fnCallbacks.length;i<l;i++){fnCallbacks[i].call(null,messageHolder);}}
this.setIsTriggeredByUserAction=function(isTriggeredByUserAction){this.isTriggeredByUserAction=isTriggeredByUserAction;return this;};this.load=function(){var messageHolder=getMessageHolder();messagesToLoad[message.type]=messagesToLoad[message.type]||priorityQueueService.create(compareMessagesByImportance);queueRequestAndExecuteAction(messagesToLoad[message.type],messageHolder,loadMessageWithHighestPriority);};this.show=function(){if(this.isTriggeredByUserAction===null){throw new Error('setIsTriggeredByUserAction() needs to be called before calling show()');}
var messageHolder=getMessageHolder();messagesToShow=messagesToShow||priorityQueueService.create(compareMessagesByImportance);queueRequestAndExecuteAction(messagesToShow,messageHolder,showMessageWithHighestPriority);};this.registerOnLoadCallback=function(callback){addCallBackHandlerByEventType(ONLOAD_KEY,callback);return this;};this.registerOnShowCallback=function(callback){addCallBackHandlerByEventType(ONSHOW_KEY,callback);return this;};this.registerOnCloseCallback=function(callback){addCallBackHandlerByEventType(ONCLOSE_KEY,callback);return this;};messageRepresentation.setOnLoadCallback(function(){var messageHolder=getMessageHolder();runAllCallBackHandlersByEventType(ONLOAD_KEY,messageHolder);});messageRepresentation.setOnShowCallback(function(representationMessageData){var messageHolder=getMessageHolder();messageHolder.message.el=representationMessageData.el;runAllCallBackHandlersByEventType(ONSHOW_KEY,messageHolder);});var me=this;messageRepresentation.setOnCloseCallback(function(){var messageHolder=getMessageHolder();messageHolder.wasTriggeredByUserAction=me.isTriggeredByUserAction;runAllCallBackHandlersByEventType(ONCLOSE_KEY,messageHolder);});}
function NonDisplayableMessage(messageIdentifier,messageName,messageContext){this.identifier=messageIdentifier;this.name=messageName;this.type='non-displayable';this.context=messageContext;this.isTriggeredByUserAction=null;this.setIsTriggeredByUserAction=function(isTriggeredByUserAction){this.isTriggeredByUserAction=isTriggeredByUserAction;return this;};this.load=function(){};this.show=function(){if(this.isTriggeredByUserAction===null){throw new Error('setIsTriggeredByUserAction() needs to be called before calling show()');}};this.registerOnLoadCallback=function(){return this;};this.registerOnShowCallback=function(){return this;};this.registerOnCloseCallback=function(){return this;};}
return{createDisplayableMessageProxy:function(message,messageRepresentation){return new DisplayableMessage(message,messageRepresentation);},createNonDisplayableMessageProxy:function(message){return new NonDisplayableMessage(message);},registerOnMessagePreLoadCallback:function(callback){messagePreLoadCallbacks.push(callback);return this;},setMessageEligibilityEvaluator:function(evaluator){if(typeof evaluator!=='function'){throw new Error('[message-auctioneer] param to setMessageEligibilityEvaluator should be function!');}
fnMessageEligibilityEvaluator=evaluator;return this;}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/pigeon.js',time:(new Date()).getTime()});Box.Application.addService('pigeon',function(application){'use strict';var ONLOAD_KEY='onLoad';var ONSHOW_KEY='onShow';var ONCLOSE_KEY='onClose';var publicApi;var messageFactoryCollectionService=application.getService('message-factory-collection');var messageRegistrationService=application.getService('message-registration-desk');var messageAuctioneerService=application.getService('message-auctioneer');var currentlyShownMessages={};var messagesSeenInCurrentSession={};var messageTypesSuppressedInCurrentSession={};var loadedMessages={};var globalCallbacks={onLoad:[],onShow:[],onClose:[]};var canCoexistWithCurrentlyShownMessagesEvaluator=null;function isShowingMessage(){var currentlyShownMessageTypes=Object.keys(currentlyShownMessages);return currentlyShownMessageTypes.length!==0;}
function canCoexistWithShownMessages(message){if(!isShowingMessage()){return true;}
if(canCoexistWithCurrentlyShownMessagesEvaluator!==null){return canCoexistWithCurrentlyShownMessagesEvaluator(currentlyShownMessages,message);}
return false;}
function getMessageIdentifier(messageName,messageType){return messageType+'_'+messageName;}
function wasMessageShownInCurrentSession(messageIdentifier,messageContext){return(messageIdentifier in messagesSeenInCurrentSession&&messageContext in messagesSeenInCurrentSession[messageIdentifier]);}
function wasMessageTypeSuppressedInCurrentSession(messageType){return(messageType in messageTypesSuppressedInCurrentSession);}
function shouldRegisterMessage(message){if((!message.canBeShownMultipleTimes&&wasMessageShownInCurrentSession(message.identifier,message.context))||(!message.isExemptFromSuppression&&wasMessageTypeSuppressedInCurrentSession(message.type))){return false;}
return true;}
function shouldApplySuppression(triggeringMessage,wasMessageTriggeredByUserAction){return(triggeringMessage.shouldStartSuppressionPeriod&&!wasMessageTriggeredByUserAction);}
function applySuppressionOnMessagesOfType(messageType){var registeredMessagesOfType=messageRegistrationService.getAllRegisteredMessagesOfType(messageType);var numMessages=registeredMessagesOfType.length;for(var i=0;i<numMessages;i++){var message=registeredMessagesOfType[i];if(!message.isExemptFromSuppression){messageRegistrationService.unregister(message.identifier,message.context);}}
messageTypesSuppressedInCurrentSession[messageType]=true;}
function isMessageLoaded(messageIdentifier,messageType){var loadedMessage=loadedMessages[messageType];return(loadedMessage&&loadedMessage.identifier===messageIdentifier);}
function unloadCurrentlyLoadedMessage(messageType){var loadedMessageRepresentationObject=loadedMessages[messageType];if(loadedMessageRepresentationObject){var representation=loadedMessageRepresentationObject.representation;loadedMessages[messageType]=null;representation.unload();}}
function getAllAutoLoadableMessagesOfType(messageType){var autoLoadableMessages=[];var registeredMessagesOfType=messageRegistrationService.getAllRegisteredMessagesOfType(messageType);var numMessages=registeredMessagesOfType.length;for(var i=0;i<numMessages;i++){var message=registeredMessagesOfType[i];if(message.shouldAutoLoad){autoLoadableMessages.push(message);}}
return autoLoadableMessages;}
function loadNextAutoLoadableMessageOfType(messageType){var autoLoadableMessages=getAllAutoLoadableMessagesOfType(messageType);autoLoadableMessages.map(function(message){var representationProxy=publicApi.createMessageRepresentationWithContext(message.name,message.type,message.context);representationProxy.load();});}
function isMessageEligible(message){return message!==null&&messageRegistrationService.get(message.identifier,message.context)!==null;}
function canShowMessageMultipleTimes(messageIdentifier,messageContext){var message=messageRegistrationService.get(messageIdentifier,messageContext);return(message)?message.canBeShownMultipleTimes:false;}
function runAllGlobalCallBackHandlersByEventType(type,messageHolder){var fnCallbacks=globalCallbacks[type];for(var i=0,l=fnCallbacks.length;i<l;i++){fnCallbacks[i].call(null,messageHolder);}}
function addGlobalCallbackHandlerByEventType(type,callback){if(typeof callback!=='function'){return;}
globalCallbacks[type].push(callback);}
function markMessageAsSeen(messageIdentifier,messageContext){if(!(messageIdentifier in messagesSeenInCurrentSession)){messagesSeenInCurrentSession[messageIdentifier]={};}
messagesSeenInCurrentSession[messageIdentifier][messageContext]=true;}
function addToCurrentlyShownMessages(message){currentlyShownMessages[message.type]=message;}
function removeFromCurrentlyShownMessages(message){delete currentlyShownMessages[message.type];}
function onMessageLoaded(messageHolder){var message=messageHolder.message;loadedMessages[message.type]={identifier:message.identifier,representation:messageHolder.representation};runAllGlobalCallBackHandlersByEventType(ONLOAD_KEY,messageHolder);}
function onMessageShown(messageHolder){var message=messageHolder.message;addToCurrentlyShownMessages(message);if(!canShowMessageMultipleTimes(message.identifier,message.context)){messageRegistrationService.unregister(message.identifier,message.context);}
markMessageAsSeen(message.identifier,message.context);runAllGlobalCallBackHandlersByEventType(ONSHOW_KEY,messageHolder);}
function onMessageClosed(messageHolder){var messageClosed=messageHolder.message;var isClosedMessageStillEligible;removeFromCurrentlyShownMessages(messageClosed);if(shouldApplySuppression(messageClosed,messageHolder.wasTriggeredByUserAction)){applySuppressionOnMessagesOfType(messageClosed.type);}
isClosedMessageStillEligible=isMessageEligible(messageClosed);if(!isClosedMessageStillEligible||!canShowMessageMultipleTimes(messageClosed.identifier,messageClosed.context)){unloadCurrentlyLoadedMessage(messageClosed.type);loadNextAutoLoadableMessageOfType(messageClosed.type);}
runAllGlobalCallBackHandlersByEventType(ONCLOSE_KEY,messageHolder);}
function onMessagePreLoad(message){if(!isMessageLoaded(message.identifier,message.type)){unloadCurrentlyLoadedMessage(message.type);}}
function init(){messageAuctioneerService.registerOnMessagePreLoadCallback(onMessagePreLoad).setMessageEligibilityEvaluator(isMessageEligible);}
publicApi={registerMessage:function(message){var representationProxy;if(shouldRegisterMessage(message)){messageRegistrationService.register(message);if(message.shouldAutoShow){representationProxy=this.createMessageRepresentationWithContext(message.name,message.type,message.context);representationProxy.setIsTriggeredByUserAction(false).show();}else if(message.shouldAutoLoad){representationProxy=this.createMessageRepresentationWithContext(message.name,message.type,message.context);representationProxy.setIsTriggeredByUserAction(false).load();}}},unregisterMessage:function(messageIdentifier,messageContext,messageType){messageRegistrationService.unregister(messageIdentifier,messageContext);if(isMessageLoaded(messageIdentifier,messageType)){unloadCurrentlyLoadedMessage(messageType);loadNextAutoLoadableMessageOfType(messageType);}},createMessageRepresentation:function(messageName,messageType){var messageContext=null;return this.createMessageRepresentationWithContext(messageName,messageType,messageContext);},createMessageRepresentationWithContext:function(messageName,messageType,messageContext){var messageIdentifier=getMessageIdentifier(messageName,messageType);var message=messageRegistrationService.get(messageIdentifier,messageContext);if(!isMessageEligible(message)||!canCoexistWithShownMessages(message)){return messageAuctioneerService.createNonDisplayableMessageProxy(message);}
var messageRepresentationFactory=messageFactoryCollectionService.get(messageType);if(messageRepresentationFactory===null){return messageAuctioneerService.createNonDisplayableMessageProxy(message);}
var messageRepresentation=messageRepresentationFactory.create(message);var proxy=messageAuctioneerService.createDisplayableMessageProxy(message,messageRepresentation);proxy.registerOnLoadCallback(onMessageLoaded);proxy.registerOnShowCallback(onMessageShown);proxy.registerOnCloseCallback(onMessageClosed);return proxy;},addMessageRepresentationFactory:function(type,factory){messageFactoryCollectionService.add(type,factory);},registerGlobalOnLoadCallback:function(callback){addGlobalCallbackHandlerByEventType(ONLOAD_KEY,callback);return this;},registerGlobalOnShowCallback:function(callback){addGlobalCallbackHandlerByEventType(ONSHOW_KEY,callback);return this;},registerGlobalOnCloseCallback:function(callback){addGlobalCallbackHandlerByEventType(ONCLOSE_KEY,callback);return this;},setCanMessagesCoexistEvaluator:function(callback){if(typeof callback==='function'){canCoexistWithCurrentlyShownMessagesEvaluator=callback;}else{throw new Error('Invalid parameter callback passed in.');}
return this;},_getRegisteredMessage:function(messageIdentifier,messageContext){return messageRegistrationService.get(messageIdentifier,messageContext);}};init();return publicApi;});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/factories/popout.js',time:(new Date()).getTime()});Box.Application.addService('popout',function(application){'use strict';var ACTION_TOGGLE_POPOUT='toggle-popout';var ACTION_LAUNCH_TOUR='launch-tour';var ACTION_CLOSE_POPOUT='close-popout';var CLASS_TOGGLE_POPOUT_BUTTON='popout-toggle-button';var ESC_KEY=27;var CLOSE_PRESS_ESC_KEY={target:'esc',action:'keypress'};var CLOSE_CLICK_TOGGLE_BUTTON={target:'helpbutton',action:'click'};var CLOSE_CLICK_ENGAGE_BUTTON={target:'engagebutton',action:'click'};var CLOSE_CLICK_IGNORE_BUTTON={target:'ignorebutton',action:'click'};var CLOSE_CLICK_OVERLAY={target:'overlay',action:'click'};var ajaxService=application.getService('ajax');var domService=application.getService('dom');var menuToggleService=application.getService('menu-toggle');var promisesService=application.getService('promises');var resinService=application.getService('resin');var screenService=application.getService('screen');var currentPopout={};var isPopoutShown=false;var menu;var resinActionAttributes;var closeTarget;function noop(){}
function getCurrentPageName(){return resinService.sanitize(resinActionAttributes.page);}
function updateResinPage(){var popoutName=currentPopout.popoutEl.getAttribute('data-popout-name');var resinPage=getCurrentPageName()+'|'+popoutName;currentPopout.popoutEl.setAttribute('data-resin-page',resinService.sanitize(resinPage));}
function initResinAttributes(){currentPopout.popoutEl.removeAttribute('data-resin-page');var resinFeatureTarget=domService.query('[data-resin-feature]',currentPopout.popoutEl);resinActionAttributes=resinService.getActionAttributes(resinFeatureTarget);updateResinPage();}
function recordUserActionProgrammatically(target,action){resinService.recordAction({application:resinService.sanitize(resinActionAttributes.application),page:currentPopout.popoutEl.getAttribute('data-resin-page'),component:'popout',feature:'popout',target:resinService.sanitize(target),action:resinService.sanitize(action)});}
function recordCloseAction(){var closeActionTarget=closeTarget||CLOSE_CLICK_OVERLAY;recordUserActionProgrammatically('close|'+closeActionTarget.target,closeActionTarget.action);closeTarget=null;}
function closePopout(){if(!isPopoutShown){return;}
menu.destroy();isPopoutShown=false;recordCloseAction();currentPopout.onCloseCallback(currentPopout.popoutData);}
function initNewMenuToggle(){var shouldCloseMenuOnBlur=true;var menuToggle=menuToggleService.create(shouldCloseMenuOnBlur);menuToggle.init();menuToggle.on('closed',closePopout);return menuToggle;}
function showPopout(){if(isPopoutShown){return;}
menu=initNewMenuToggle();var togglePopoutEl=domService.query('.'+CLASS_TOGGLE_POPOUT_BUTTON,currentPopout.popoutEl);menu.showMenu(togglePopoutEl);isPopoutShown=true;recordUserActionProgrammatically('loaded','programmatic');var callbackData=$.extend({},currentPopout.popoutData,{el:currentPopout.popoutEl});currentPopout.onShowCallback(callbackData);}
function onTogglePopoutButtonClicked(event){if(isPopoutShown){closeTarget=CLOSE_CLICK_TOGGLE_BUTTON;}else{event.stopPropagation();recordUserActionProgrammatically('open|helpbutton','click');var contextualMessageService=application.getService('contextual-message');contextualMessageService.createMessageRepresentationWithContext(currentPopout.popoutData.name,'popout',currentPopout.popoutData.context).setIsTriggeredByUserAction(true).show();}}
function onLaunchTourButtonClicked(tourName){if(!tourName){return;}
closeTarget=CLOSE_CLICK_ENGAGE_BUTTON;menu.closeMenu();var contextualMessageService=application.getService('contextual-message');contextualMessageService.createMessageRepresentation(tourName,'fullscreentour').setIsTriggeredByUserAction(true).show();}
function onClosePopoutButtonClicked(){closeTarget=CLOSE_CLICK_IGNORE_BUTTON;menu.closeMenu();}
function mouseDownHandler(event){var element=event.target||event.srcElement;if(!element.hasAttribute('data-action')){element=domService.getNearest(event.target,'[data-action]');if(element===null){return;}}
if(!element){return;}
var action=element.getAttribute('data-action');switch(action){case ACTION_TOGGLE_POPOUT:onTogglePopoutButtonClicked(event);break;case ACTION_LAUNCH_TOUR:var tourName=element.getAttribute('data-tour');onLaunchTourButtonClicked(tourName);break;case ACTION_CLOSE_POPOUT:onClosePopoutButtonClicked();break;}}
function keyUpHandler(event){var element=event.target||event.srcElement;var action=element.getAttribute('data-action');if(action===ACTION_TOGGLE_POPOUT){if(event.keyCode===ESC_KEY&&isPopoutShown){closeTarget=CLOSE_PRESS_ESC_KEY;}}}
function attachPopoutListeners(){domService.on(currentPopout.popoutEl,'mousedown',mouseDownHandler);domService.on(currentPopout.popoutEl,'keyup',keyUpHandler);}
function detachPopoutListeners(){domService.off(currentPopout.popoutEl,'mousedown',mouseDownHandler);domService.off(currentPopout.popoutEl,'keyup',keyUpHandler);}
function removeCurrentPopout(){if(!currentPopout.popoutEl){return;}
detachPopoutListeners();domService.remove(currentPopout.popoutEl);currentPopout={};}
function finishPopoutLoadingSetupAndRunCallbacks(popout,popoutEl){detachPopoutListeners();currentPopout=popout;currentPopout.popoutEl=popoutEl||domService.query('.contextual-popout[data-popout-name="'+popout.popoutData.name+'"]');initResinAttributes();attachPopoutListeners();popout.onLoadCallback(popout.popoutData);}
function loadPopout(popout){var runmode=popout.popoutData.templateFetchEndpoint;var params={id:popout.popoutData.id,identifier:popout.popoutData.identifier,isHighDensityDisplay:screenService.isHighDensity()};var popoutEl=domService.query('.contextual-popout[data-popout-name="'+popout.popoutData.name+'"]');var popoutMountNode=domService.query('.contextual-popout-container')||document.body;if(popoutEl){finishPopoutLoadingSetupAndRunCallbacks(popout,popoutEl);return promisesService.createResolved();}
return ajaxService.get(runmode,params).then(function popoutContentReceived(response){var popoutFragment=domService.createFragmentFromHtml(response.data.html);popoutMountNode.appendChild(popoutFragment);finishPopoutLoadingSetupAndRunCallbacks(popout);return;});}
function Popout(popoutData){this.popoutData=popoutData;this.popoutEl=null;this.onLoadCallback=noop;this.onShowCallback=noop;this.onCloseCallback=noop;}
Popout.prototype={load:function(){return loadPopout(this);},show:function(){this.load().then(showPopout);},unload:function(){removeCurrentPopout();},setOnLoadCallback:function(callback){if(typeof callback==='function'){this.onLoadCallback=callback;}},setOnShowCallback:function(callback){if(typeof callback==='function'){this.onShowCallback=callback;}},setOnCloseCallback:function(callback){if(typeof callback==='function'){this.onCloseCallback=callback;}}};return{create:function(popoutData){return new Popout(popoutData);}};});Box.Timing.execution.push({name:'js/services/amsterdam/contextual-message/factories/banner.js',time:(new Date()).getTime()});Box.Application.addService('banner',function(application){'use strict';var BANNER_ANCHOR_ELEMENT_ID='contextual-message-banner-anchor';var CLASS_HIDDEN='hidden';var ajaxService=application.getService('ajax');var domService=application.getService('dom');var promisesService=application.getService('promises');var resinService=application.getService('resin');var screenService=application.getService('screen');var currentBanner=null;var bannerAnchorEl;var resinActionAttributes;function noop(){}
function getCurrentBannerName(){return(currentBanner!==null)?currentBanner.bannerData.name:null;}
function getCurrentPageName(){return resinService.sanitize(resinActionAttributes.page);}
function recordUserActionProgrammatically(target,action){resinService.recordAction({application:resinService.sanitize(resinActionAttributes.application),page:currentBanner.bannerEl.getAttribute('data-resin-page'),component:'banner',feature:'banner',target:resinService.sanitize(target),action:resinService.sanitize(action)});}
function updateResinPage(){var resinPage=getCurrentPageName()+'|'+getCurrentBannerName();currentBanner.bannerEl.setAttribute('data-resin-page',resinService.sanitize(resinPage));}
function initResinAttributes(){currentBanner.bannerEl.removeAttribute('data-resin-page');var resinTarget=currentBanner.bannerEl.firstChild;resinActionAttributes=resinService.getActionAttributes(resinTarget);updateResinPage();}
function doHideCurrentBanner(){domService.addClass(currentBanner.bannerEl,CLASS_HIDDEN);}
function doShowCurrentBanner(){domService.removeClass(currentBanner.bannerEl,CLASS_HIDDEN);}
function closeBanner(){if(currentBanner){detachBannerListeners();doHideCurrentBanner();currentBanner.onCloseCallback();}
currentBanner=null;}
function mouseUpHandler(event){var element=event.target||event.srcElement;var action=element.getAttribute('data-action');if(action==='close-banner'){recordUserActionProgrammatically('close|esc','keypress');closeBanner();}}
function attachBannerListeners(){domService.on(currentBanner.bannerEl,'mouseup',mouseUpHandler);}
function detachBannerListeners(){domService.off(currentBanner.bannerEl,'mouseup',mouseUpHandler);}
function showBanner(){attachBannerListeners();doShowCurrentBanner();initResinAttributes();recordUserActionProgrammatically('loaded','programmatic');var callbackData=$.extend({},currentBanner.bannerData,{el:currentBanner.bannerEl});currentBanner.onShowCallback(callbackData);}
function getBannerAnchorEl(){if(!bannerAnchorEl){bannerAnchorEl=document.getElementById(BANNER_ANCHOR_ELEMENT_ID);}
return bannerAnchorEl?bannerAnchorEl:null;}
function loadBanner(banner){var bannerEl=domService.query('[data-banner-name="'+banner.bannerData.name+'"]');var runmode=banner.bannerData.templateFetchEndpoint;var params={id:banner.bannerData.id,identifier:banner.bannerData.identifier,isHighDensityDisplay:screenService.isHighDensity()};if(bannerEl){banner.onLoadCallback(banner.bannerData);return promisesService.createResolved();}
var anchorEl=getBannerAnchorEl();if(anchorEl===null){return promisesService.createRejected('No anchor element found on the page');}
return ajaxService.get(runmode,params).then(function bannerContentReceived(response){var bannerFragment=domService.createFragmentFromHtml(response.data.html);anchorEl.appendChild(bannerFragment);return;}).then(function executeLoadCallbacks(){banner.onLoadCallback(banner.bannerData);return;});}
function Banner(bannerData){this.bannerData=bannerData;this.bannerEl=null;this.onLoadCallback=noop;this.onShowCallback=noop;this.onCloseCallback=noop;}
Banner.prototype={load:function(){return loadBanner(this);},show:function(){var bannerName=this.bannerData.name;currentBanner=this;this.load().then(function(){currentBanner.bannerEl=domService.query('[data-banner-name="'+bannerName+'"]');showBanner();});},unload:function(){},setOnLoadCallback:function(callback){if(typeof callback==='function'){this.onLoadCallback=callback;}},setOnShowCallback:function(callback){if(typeof callback==='function'){this.onShowCallback=callback;}},setOnCloseCallback:function(callback){if(typeof callback==='function'){this.onCloseCallback=callback;}},_close:closeBanner};return{create:function(bannerData){return new Banner(bannerData);}};});Box.Timing.execution.push({name:'js/services/amsterdam/slide-carousel.js',time:(new Date()).getTime()});Box.Application.addService('slide-carousel',function(application){'use strict';var domService=application.getService('dom');var ACTIVE_CLASS='is-active';var CHANGE_SLIDE_DELAY=300;var TRANSITION_LEFT_CLASS='transition-left';var TRANSISION_RIGHT_CLASS='transition-right';var SLIDE_NAME_ATTRIBUTE='data-slide-name';function generateIdsAndPagination(carousel){carousel.isNavigable=carousel.paginationContainerEl.getAttribute('data-navigable')!=='false';while(carousel.paginationContainerEl.firstChild){carousel.paginationContainerEl.removeChild(carousel.paginationContainerEl.firstChild);}
var paginationIcon;for(var i=0,len=carousel.slideEls.length;i<len;i++){var slideEl=carousel.slideEls[i];slideEl.setAttribute('data-slide-num',i);paginationIcon=document.createElement('li');paginationIcon.setAttribute('data-type','go-to-slide');paginationIcon.setAttribute('data-slide-num',i);if(domService.hasClass(slideEl,ACTIVE_CLASS)){paginationIcon.className=ACTIVE_CLASS;carousel.currentSlideNum=i;carousel.currentSlideName=slideEl.getAttribute(SLIDE_NAME_ATTRIBUTE);}
carousel.paginationContainerEl.appendChild(paginationIcon);}
carousel.paginationEls=carousel.paginationContainerEl.childNodes;}
function initProgressBar(carousel){var progressBarService=application.getService('progress-circle');carousel.progressBar=progressBarService.create({element:carousel.progressEl,total:carousel.slideEls.length});}
function resetSlidePositions(carousel){var slideEl;for(var i=0,len=carousel.slideEls.length;i<len;i++){slideEl=carousel.slideEls[i];domService.removeClass(slideEl,TRANSITION_LEFT_CLASS);domService.removeClass(slideEl,TRANSISION_RIGHT_CLASS);if(i<carousel.currentSlideNum){domService.addClass(slideEl,TRANSITION_LEFT_CLASS);}
if(i>carousel.currentSlideNum){domService.addClass(slideEl,TRANSISION_RIGHT_CLASS);}}}
function resetAnimatedGif(slideEl){var presentationContentEl=domService.query('.presentation-content',slideEl);if(presentationContentEl){var backgroundImage=domService.getComputedCSS(presentationContentEl)['background-image'];var gifURLPattern=/url\(['"]?(.+\.gif).*['"]?\)/;var matches;if((matches=gifURLPattern.exec(backgroundImage))!==null){presentationContentEl.style.backgroundImage='url('+matches[1]+'?rnd='+Math.random()+')';}}}
function mouseUpHandler(carousel){return function(event){var element=event.target||event.srcElement;var elementType=element.getAttribute('data-type');if(!elementType||!carousel.isNavigable){return;}
switch(elementType){case'go-to-slide':carousel.goToSlide(Number(element.getAttribute('data-slide-num')));break;case'next-slide':carousel.goToNextSlide();break;case'prev-slide':carousel.goToPrevSlide();break;default:return;}};}
function SlideCarousel(wrapperEl){this.wrapperEl=wrapperEl;this.isCurrentlyChangingSlides=false;this.isNavigable=true;this.slideContainerEl=domService.query('.slides',this.wrapperEl);this.slideEls=domService.queryAll('.slides > li',this.wrapperEl);this.paginationContainerEl=domService.query('.slides-pagination',this.wrapperEl);this.paginationEls=null;this.progressEl=domService.query('.progress',this.wrapperEl);this.currentSlideNum=0;this.currentSlideName=this.slideEls[0].getAttribute(SLIDE_NAME_ATTRIBUTE);generateIdsAndPagination(this);resetSlidePositions(this);this.mouseUpHandlerRef=mouseUpHandler(this);domService.on(this.paginationContainerEl,'mouseup',this.mouseUpHandlerRef);if(this.progressEl&&this.slideEls.length){initProgressBar(this);}}
SlideCarousel.prototype={goToSlide:function(incomingSlideNum){if(incomingSlideNum>=this.slideEls.length||incomingSlideNum<0||this.isCurrentlyChangingSlides){return false;}
this.isCurrentlyChangingSlides=true;var incomingPaginationEl=this.paginationEls[incomingSlideNum];var incomingSlideEl=this.slideEls[incomingSlideNum];var outgoingPaginationEl=this.paginationEls[this.currentSlideNum];var outgoingSlideEl=this.slideEls[this.currentSlideNum];domService.removeClass(incomingSlideEl,TRANSITION_LEFT_CLASS);domService.removeClass(incomingSlideEl,TRANSISION_RIGHT_CLASS);var outgoingClass=incomingSlideNum>this.currentSlideNum?TRANSITION_LEFT_CLASS:TRANSISION_RIGHT_CLASS;domService.addClass(outgoingSlideEl,outgoingClass);domService.removeClass(outgoingPaginationEl,ACTIVE_CLASS);domService.removeClass(outgoingSlideEl,ACTIVE_CLASS);domService.addClass(incomingPaginationEl,ACTIVE_CLASS);domService.addClass(incomingSlideEl,ACTIVE_CLASS);this.currentSlideNum=incomingSlideNum;this.currentSlideName=incomingSlideEl.getAttribute(SLIDE_NAME_ATTRIBUTE);resetSlidePositions(this);resetAnimatedGif(incomingSlideEl);var me=this;setTimeout(function(){me.isCurrentlyChangingSlides=false;},CHANGE_SLIDE_DELAY);if(this.progressBar){this.progressBar.updateProgress(this.currentSlideNum);}
return true;},goToNextSlide:function(rollover){var nextSlideNum=this.currentSlideNum+1;return this.goToSlide(rollover?nextSlideNum%this.slideEls.length:nextSlideNum);},goToPrevSlide:function(rollover){var nextSlideNum=this.currentSlideNum-1;this.goToSlide(rollover&&nextSlideNum<0?this.slideEls.length-1:nextSlideNum);},getCurrentSlideNum:function(){return this.currentSlideNum;},isOnLastSlide:function(){return(this.currentSlideNum===this.slideEls.length-1);},getCurrentSlideName:function(){return this.currentSlideName||'';},destroy:function(){domService.off(this.paginationContainerEl,'mouseup',this.mouseUpHandlerRef);}};return{create:function(wrapperEl){return new SlideCarousel(wrapperEl);}};});Box.Timing.execution.push({name:'js/services/priority-queue.js',time:(new Date()).getTime()});Box.Application.addService('priority-queue',function(){'use strict';function PriorityQueue(comparator){var queue=[];var needsSorting=false;function sortQueueIfNeeded(){if(needsSorting){queue.sort(comparator);needsSorting=false;}}
return{queue:function(value){queue.push(value);needsSorting=true;},peek:function(){sortQueueIfNeeded();return(queue.length!==0)?queue[0]:null;},dequeue:function(){sortQueueIfNeeded();return(queue.length!==0)?queue.shift():null;},clear:function(){queue=[];needsSorting=false;}};}
return{create:function(comparator){return new PriorityQueue(comparator);}};});Box.Timing.execution.push({name:'js/services/screen.js',time:(new Date()).getTime()});Box.Application.addService('screen',function(){'use strict';return{isHighDensity:function(){return(window.devicePixelRatio>=2||(window.matchMedia&&window.matchMedia('(-webkit-min-device-pixel-ratio: 2),(min-resolution: 192dpi)').matches));}};});;Box.Timing.execution.push({name:'done',time:(new Date()).getTime()});